Wrap package for CppUTest 4.0
mesonbuild/cpputest pull request #1
Opened 2020-09-21 05:29 UTC by michaelbrockus

Wrap package for CppUTest. There are two dependencies declared in the package one for the test framework and the other for the framework extensions.

2020-09-23 22:05 UTC, legeana requested changes

2020-09-23 22:05 UTC, legeana commented on meson.build
> +if get_option('extinctions') == true
`if X == true` can generally be rewritten as `if X` I believe and it looks much better.

2020-09-23 22:05 UTC, legeana commented on src/meson.build
> +if get_option('extinctions') == true
Same, please consider using `if get_option('...')` without `== true`.

2020-09-23 22:05 UTC, legeana commented on upstream.wrap
> +directory = cpputest
I believe it should be `cpputest-4.0` based on the directory name in the archive.

2020-09-24 01:45 UTC, michaelbrockus commented
Sure I will get on that

2020-09-24 01:50 UTC, michaelbrockus commented
Also fixed.

2020-09-25 23:20 UTC, merged